const ACTION_TYPES = {
  // TASK ACTIONS
  CREATE_TASK: 'CREATE_TASK',
  GET_ALL_TASK: 'GET_ALL_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',

  // CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  // CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  // CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
};

export default ACTION_TYPES;
